apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    app: rest-api-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.restApiApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.restApiApp.name }}
    spec:
      containers:
        - name: {{ .Values.restApiApp.name }}
          image: {{ .Values.restApiApp.image.repository }}:{{ .Values.restApiApp.image.tag }}
          env:
            - name: MYSQL_REMOTE_HOST_NAME
              value: sql.freedb.tech
            - name: MYSQL_GUEST_PORT
              value: "3306"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.restApiApp.restPort }}
