apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.restApiApp.serviceName }}
spec:
  selector:
    app: {{ .Values.restApiApp.name }}
  ports:
  - name: rest-api-port-{{ .Values.restApiApp.restPort }}
    protocol: "TCP"
    port: {{ .Values.restApiApp.restPort }}
    targetPort: {{ .Values.restApiApp.restPort }}
  type: {{ .Values.service.type }}