apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flaskImage.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.flaskImage.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.flaskImage.name }}
    spec:
      containers:
        - name: {{ .Values.flaskImage.name }}
          image: {{ .Values.flaskImage.image.repository }}:{{ .Values.flaskImage.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.flaskImage.port }}