apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flaskImage.name }}-service
spec:
  selector:
    app: {{ .Values.flaskImage.name }}
  ports:
  - name: port-{{ .Values.flaskImage.port }}
    protocol: "TCP"
    port: {{ .Values.flaskImage.port }}
    targetPort: {{ .Values.flaskImage.port }}
  type: {{ .Values.type }}