apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-claim
  labels:
    app: {{ .Values.mysql.name }}
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi