##############################
# This Section - Not In Used #
##############################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - name: {{ .Values.mysql.name }}
      protocol: "TCP"
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  type: { { .Values.service.type } }