##############################
# This Section - Not In Used #
##############################
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_USER: { { .Values.secret.mysqlRootUser | b64enc } }
  MYSQL_ROOT_PASSWORD: { { .Values.secret.mysqlRootPassword | b64enc } }
  MYSQL_DATABASE: { { .Values.secret.mysqlDatabase | b64enc } }
  MYSQL_USER: { { .Values.secret.mysqlUser | b64enc } }
  MYSQL_PASSWORD: { { .Values.secret.mysqlPassword | b64enc } }