##############################
# This Section - Not In Used #
##############################
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-mysql
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    hostPath:
        path: /tmp/data