###################################################################################################################################
# Note - This Dockerfile not in used, Because we use with `docker-compose-<Number>.yml` and call to remote image - `mysql:8.0.32` #
###################################################################################################################################

# From Image #
FROM mysql:${IMAGE_TAG}

# User Name #
ENV MYSQL_USER_NAME=${MYSQL_USER}

# Password #
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}

# Schema Name #
ENV MYSQL_SCHEMA_NAME=${MYSQL_SCHEMA_NAME}

# Expose Port #
EXPOSE 3306

# Run Command #
CMD ["mysqld"]
