version: "3.8"
services:
  database:
    env_file:
      - ../.env
    image: "mysql:${MYSQL_TAG}"
    container_name: ${MYSQL_CONTAINER_NAME}
    hostname: ${MYSQL_HOST_NAME}
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SCHEMA_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_GUEST_PORT}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 45s
      retries: 10
    command: mysqld
  rest_api:
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ../.env
    image: "dingolan/devops_experts_final_project:${REST_TAG}${IMAGE_TAG_1}"
    container_name: ${REST_CONTAINER_NAME}
    hostname: ${REST_HOST_NAME}
    ports:
      - "5000:5000"
    build:
      context: ..
      args:
        MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
        MYSQL_GUEST_PORT: ${MYSQL_GUEST_PORT}
      dockerfile: /Dockerfiles/Dockerfile_rest_api_for_docker
    environment:
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_GUEST_PORT: ${MYSQL_GUEST_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "ping -c 1 rest_api" ]
      interval: 2s
      timeout: 10s
      retries: 5
    links:
      - database