version: "3.9"
services:
  database:
    env_file:
      - ../.env
    image: "mysql:${MYSQL_TAG}"
    container_name: ${MYSQL_CONTAINER_NAME}
    hostname: ${MYSQL_HOST_NAME}
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SCHEMA_NAME}
      MYSQL_USER_NAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: mysqld
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 45s
      retries: 10
  rest_api:
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ../.env
    image: "dingolan/devops_experts_final_project:${REST_TAG}${IMAGE_TAG_2}"
    container_name: ${REST_CONTAINER_NAME}
    ports:
      - "5000:5000"
    build:
      context: ..
      dockerfile: /Dockerfiles/Dockerfile_rest_api
    hostname: ${REST_HOST_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "ping -c 1 rest_api" ]
      interval: 2s
      timeout: 10s
      retries: 5
    links:
      - database
  docker_backend_testing:
    depends_on:
      rest_api:
        condition: service_healthy
    env_file:
      - ../.env
    image: "dingolan/devops_experts_final_project:${PY_TAG}${IMAGE_TAG_2}"
    container_name: ${DOCKER_BACKEND_TESTING_CONTAINER_NAME}
    ports:
      - "5000"
    build:
      context: ..
      dockerfile: /Dockerfiles/Dockerfile_docker_backend_testing
    hostname: ${DOCKER_BACKEND_TESTING_HOST_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "ping -c 1 docker_backend_testing" ]
      interval: 2s
      timeout: 10s
      retries: 5
    links:
      - database
      - rest_api