# From Image #
FROM mysql:8.0.31

# User Name #
ENV MYSQL_USER_NAME=${MYSQL_USER_NAME}

# Password #
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}

# Schema Name #
ENV MYSQL_SCHEMA_NAME=${MYSQL_SCHEMA_NAME}

# Expose Port #
EXPOSE 3306

# Run Command #
CMD ["mysqld"]
