# From Image #
FROM python:3.10.5

RUN apk add --no-cache  build-base linux-headers dos2unix vim

# Set working directory in container #
WORKDIR /DevOps_Experts_Final_Project

# Copy `docker_backend_testing.py` to the container #
COPY ../Clean         /DevOps_Experts_Final_Project/Clean
COPY ../Config        /DevOps_Experts_Final_Project/Config
COPY ../DB            /DevOps_Experts_Final_Project/DB
COPY ../Driver        /DevOps_Experts_Final_Project/Driver
COPY ../HTML_Files    /DevOps_Experts_Final_Project/HTML_Files
COPY ../Packages      /DevOps_Experts_Final_Project/Packages
COPY ../REST_API      /DevOps_Experts_Final_Project/REST_API
COPY ../Testing       /DevOps_Experts_Final_Project/Testing
COPY ../Web_Interface /DevOps_Experts_Final_Project/Web_Interface

# dos2unix - change file encoding
RUN dos2unix /DevOps_Experts_Final_Project/Testing/start_testing.sh

# Add Permission #
RUN chmod +x /DevOps_Experts_Final_Project/Testing/start_testing.sh

# Pip Commands #
RUN python -m pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r /DevOps_Experts_Final_Project/Packages/requirements.txt


# Run Command #
CMD ["/bin/sh", "/DevOps_Experts_Final_Project/Testing/start_testing.sh"]
