version: "3.9"
services:
  database:
    env_file:
      - ../.env
    image: "mysql:8.0.32"
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_SCHEMA_NAME: ${MYSQL_SCHEMA_NAME}
      MYSQL_USER_NAME: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command:
      - mysqld
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 10s
      retries: 5

  python:
    env_file:
      - ../.env
    image: "dingolan/devops_experts_final_project:${PY_TAG}${IMAGE_TAG}"
    container_name: ${PYTHON_CONTAINER_NAME}
    ports:
      - "5000:5000"
    hostname: python
    healthcheck:
      test: [ "CMD-SHELL", "ping -c 1 python" ]
      interval: 2s
      timeout: 10s
      retries: 5
    build:
      context: ..
      dockerfile: /Dockerfiles/Dockerfile_Python
    volumes:
      - ../Clean:/DevOps_Experts_Final_Project/Clean
      - ../Config:/DevOps_Experts_Final_Project/Config
      - ../DB:/DevOps_Experts_Final_Project/DB
      - ../Driver:/DevOps_Experts_Final_Project/Driver
      - ../HTML_FILES:/DevOps_Experts_Final_Project/HTML_FILES
      - ../Packages:/DevOps_Experts_Final_Project/Packages
      - ../REST_API:/DevOps_Experts_Final_Project/REST_API
      - ../Testing:/DevOps_Experts_Final_Project/Testing
      - ../Web_Interface:/DevOps_Experts_Final_Project/Web_Interface
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
