replicaCount: 5

flaskImage:
  name: rest-api-application
  image:
    repository: dingolan/devops_experts_final_project
    tag: rest_api_version_latest_3
    pullPolicy: Always
  port: 5000

mysql:
  name: mysql
  image:
    repository: mysql:8.0.32
    tag: 8.0.32
    pullPolicy: Always
  port: 3306

type: LoadBalancer